version: '3.3'

networks:
  web:
    external: true

services:
  loops:
    image: jupyter/scipy-notebook:lab-4.0.2
    command:
      [
        'jupyter',
        'lab',
        '--port=8888',
        '--no-browser',
        "--ServerApp.token=''",
        "--ServerApp.password=''",
        '/workspaces/loops/notebooks/'
      ]
    ports:
      - 15015:8888
    volumes:
      - ..:/workspaces/loops/
